### ISSUE TITLE
add covering tests for abq test and abq work

### ISSUE THREAD

**Issue by michaelglass** [rwx-research/rspec-abq#44]
add golden tests recording
- stdout
- stderr
- and status code

for 
- `abq test`
- and `abq work`

with
- a group of successful tests
- and a group of failing tests
to the matrix.

should we use a testing framework here?

**Comment by dan-manges** [comment]
In #47 are we separating stdout and stderr and checking the status code? It may not be necessary, but I thought it sounded like a good idea.
