### ISSUE TITLE
investigate compatibility with common rspec plugin gems

### ISSUE THREAD

**Issue by michaelglass** [rwx-research/rspec-abq#67]
I guess I'd like to set up test harnesses for each of these gems to ensure they play nice with `rspec-abq`. Is that overkill? I'd say _maybe_ for gems that just add matchers and don't muck with execution, and _probably not_ for gems that muck with execution order, (e.g. rspec-retry)

- rspec-retry
- rspec-rails
- buildkite-test_collector
- simplecov
- rspec-instrumentation-matcher
- rspec-json_expectations
- rspec_junit_formatter
- rspec-sidekiq
- shoulda-matchers
- test-prof
- others?

**Comment by dan-manges** [comment]
We'll revisit this as we encounter any issues.
